version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - chmod +x mvnw
  build:
    commands:
      # MAVEN_CONFIG is set to /root/.m2 is CodeBuild Dockerfile which breaks the mvn usage
      # see: https://github.com/aws/aws-codebuild-docker-images/issues/237
      - export MAVEN_CONFIG=''
      - ./mvnw -B package
