spring:
  application:
    name: echo-service
    majorVersion: 1

server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}/v${spring.application.majorVersion}
  compression:
    mime-types: application/javascript,application/json,application/xml,text/css,text/html,text/plain,text/xml
    enabled: true

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: "*"
    enabled-by-default: true
